<a href="https://colab.research.google.com/github/101kbps/exercicios/blob/main/TrabalhoBigData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler 
from sklearn.cluster import KMeans


In [10]:
from sklearn import datasets

iris = datasets.load_iris()

In [11]:
base_iris =pd.read_csv('base_iris.csv' , sep = ';')

In [12]:
base_iris.head()

sepal length  sepal width  petal length  petal width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [13]:
base_iris.shape #saber a extensão do arquivo, ou seja são 150 linhas em 5 colunas

(150, 5)

In [14]:
base_iris['Class'].unique()#retorna os valores unicos da coluna class (ou seja, quantos tipos diferentes tem)

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

realizando o agrupamento por tipo (petalas)

In [16]:
x_petala = base_iris.iloc[:,[2,3]].values #usando iloc pra mostrar todos, 2,3 que são as colunas e values pra mostrar os valores
x_petala[:10] #:10 pra limitar o número de resultados a 10

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1]])

normalizando os dados para por no mesmo padrão os dados obtidos (quando os dados estão muito distantes uns dos outros)


In [17]:
normalizar_dados = StandardScaler()
x_petala = normalizar_dados.fit_transform(x_petala) #transformação das variaveis. X_petala recebe normalizar dados
x_petala[:10]


array([[-1.3412724 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.39813811, -1.31297673],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.17067529, -1.05003079],
       [-1.3412724 , -1.18150376],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.2844067 , -1.4444497 ]])

calculando o numero de cluster (usando o WCSS - que é a soma da distância quadrada entre cada ponto e o centroide de um cluster







In [19]:
wcss_petala =[] #cria uma lista vazia
for i in range(1,11):
  kmeans_petala= KMeans(n_clusters=i, random_state=0) #executa o kmeans para todos os clusters e random state =0 para fixar e obter os mesmos resultados
  kmeans_petala.fit(x_petala) #realiza o treinamento
  wcss_petala.append(kmeans_petala.inertia_) #adiciona os valores de wcss
  

In [22]:
for i in range(len(wcss_petala)): #vendo o wcss
  print('Cluster:',i,'- Valor do wcss:', wcss_petala[i])

Cluster: 0 - Valor do wcss: 300.0000000000001
Cluster: 1 - Valor do wcss: 54.14584701344988
Cluster: 2 - Valor do wcss: 18.046983891906276
Cluster: 3 - Valor do wcss: 12.307440251261843
Cluster: 4 - Valor do wcss: 9.181131495513899
Cluster: 5 - Valor do wcss: 7.215096212730807
Cluster: 6 - Valor do wcss: 6.026593155951448
Cluster: 7 - Valor do wcss: 5.173315218915379
Cluster: 8 - Valor do wcss: 4.423975871969686
Cluster: 9 - Valor do wcss: 3.9139417830543204


criando o grafico para visualização

In [23]:
grafico_cotovelo_petala = px.line( x= range(1,11), y= wcss_petala) #mostra visualmente a quantidade de clusters que devem ser criadas no caso avaliado
grafico_cotovelo_petala.show() #3 clusters é a quantidade ideal neste caso

In [24]:
kmeans_petala = KMeans(n_clusters = 3, random_state=0)
label_cluster_petala =kmeans_petala.fit_predict(x_petala)


In [25]:
label_cluster_petala

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [26]:
centroides_petala =kmeans_petala.cluster_centers_
centroides_petala

array([[-1.30487835, -1.25512862],
       [ 1.02813193,  1.12749028],
       [ 0.30564587,  0.16609419]])

In [30]:
grafico_petala =px.scatter(x =x_petala[:,0],y = x_petala [:,1], color = label_cluster_petala) #grafico de agrupamento de caracteristicas do tam e com das petalas
grafico_centroide_petala = px.scatter(x = centroides_petala[:,0], y =centroides_petala[:,1], size = [7,7,7])
grafico_final_petala = go.Figure(data = grafico_petala.data + grafico_centroide_petala.data)
grafico_final_petala.show()

In [28]:
x_sepala = base_iris.iloc[:,[0,1]].values
x_sepala[:10]


array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1]])

In [31]:
wcss_sepala =[] #cria uma lista vazia
for i in range(1,11):
  kmeans_sepala= KMeans(n_clusters=i, random_state=0) #executa o kmeans para todos os clusters e random state =0 para fixar e obter os mesmos resultados
  kmeans_sepala.fit(x_sepala) #realiza o treinamento
  wcss_sepala.append(kmeans_sepala.inertia_)

In [32]:
for i in range(len(wcss_sepala)): #vendo o wcss
  print('Cluster:',i,'- Valor do wcss:', wcss_sepala[i])

Cluster: 0 - Valor do wcss: 130.18093333333337
Cluster: 1 - Valor do wcss: 57.98240604207879
Cluster: 2 - Valor do wcss: 37.12370212765957
Cluster: 3 - Valor do wcss: 27.98254281735862
Cluster: 4 - Valor do wcss: 20.971913367009606
Cluster: 5 - Valor do wcss: 17.238695238095236
Cluster: 6 - Valor do wcss: 14.631909607059608
Cluster: 7 - Valor do wcss: 12.911711915446565
Cluster: 8 - Valor do wcss: 11.059663725936947
Cluster: 9 - Valor do wcss: 9.449454365079365


In [33]:
grafico_cotovelo_sepala = px.line( x= range(1,11), y= wcss_sepala) #mostra visualmente a quantidade de clusters que devem ser criadas no caso avaliado
grafico_cotovelo_sepala.show()

In [39]:
kmeans_sepala = KMeans(n_clusters = 3, random_state=0)
label_cluster_sepala =kmeans_sepala.fit_predict(x_sepala)

In [41]:
label_cluster_sepala

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)

In [42]:
centroides_sepala =kmeans_sepala.cluster_centers_
centroides_sepala

array([[5.77358491, 2.69245283],
       [5.006     , 3.418     ],
       [6.81276596, 3.07446809]])

In [45]:
grafico_sepala =px.scatter(x =x_sepala[:,0],y = x_sepala [:,1], color = label_cluster_sepala) 
grafico_centroide_sepala = px.scatter(x = centroides_sepala[:,0], y =centroides_sepala[:,1], size = [7,7,7])
grafico_final_sepala = go.Figure(data = grafico_sepala.data + grafico_centroide_sepala.data)
grafico_final_sepala.show()